{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.databinding",
    "module": "baseLibrary",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "baseLibrary-4.2.0.jar",
          "url": "baseLibrary-4.2.0.jar",
          "size": 16046,
          "sha512": "74b59f7c27977d7bdca07a9ff084746eb2b1a827f915aeaece35f116d4d862828536273d04af83015cd72b8c28b3f35f5366de4506fdaa2df81f6e0935a51854",
          "sha256": "4f63076385e64eb85639e550ecbef3852180d7394638416e18d58f2895001531",
          "sha1": "60a87775da182d9d6156d6e0fd7da74a9aced2ed",
          "md5": "8c45f058c925a80190392db7b6f4e05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-4.2.0.jar",
          "url": "baseLibrary-4.2.0.jar",
          "size": 16046,
          "sha512": "74b59f7c27977d7bdca07a9ff084746eb2b1a827f915aeaece35f116d4d862828536273d04af83015cd72b8c28b3f35f5366de4506fdaa2df81f6e0935a51854",
          "sha256": "4f63076385e64eb85639e550ecbef3852180d7394638416e18d58f2895001531",
          "sha1": "60a87775da182d9d6156d6e0fd7da74a9aced2ed",
          "md5": "8c45f058c925a80190392db7b6f4e05d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-4.2.0-javadoc.jar",
          "url": "baseLibrary-4.2.0-javadoc.jar",
          "size": 70083,
          "sha512": "c21f905f5055fa2726344f3eae2433738a63794ee8ee87ed6d6ee4aced6d6f68582042d067b8c27b587431a87ab3cbc9a0e826c6cff77e155c753e6481febde7",
          "sha256": "9149224cd4cbe82fe021964705e8d56aca5d3a2017a4870af78cf82b9190faf9",
          "sha1": "721f959dffa8f516abc493e31a2416821d52e041",
          "md5": "41bec3efdd702fc6caa22468c6c4047f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-4.2.0-sources.jar",
          "url": "baseLibrary-4.2.0-sources.jar",
          "size": 45860,
          "sha512": "a39f23a81cf8012bb3c07879a6f26a80335537c56b62a7f375db352b25ad2b0ca466ce952a04ea92315889a58a8dca40b6da4a472e4ac24cb0f7b5c94766d0b4",
          "sha256": "d4d521fb39fb2836dc02d057b51927b512d0877195beb858c959bd4ac1e45138",
          "sha1": "f719fafa4a07e0cf70dc4f868214a4b14c22ca3a",
          "md5": "58b5fc888076a24d1c6488a6aee993cc"
        }
      ]
    }
  ]
}
