{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android",
    "module": "signflinger",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "signflinger-4.2.0.jar",
          "url": "signflinger-4.2.0.jar",
          "size": 15208,
          "sha512": "aa911c80e37ee306ef0932954458b5351651de60ed82deac17262a57e8c57f65ff2d7bbdb242cfa53c8ee9008e20c06689bfc7dc0e840baa94bd6ae85f9c49e5",
          "sha256": "87d369493521886d017cbcab0d1be658bab8c006dfb8aebd868b19127839ff22",
          "sha1": "99e94d23459e582bbca3c266465f8cdd1fe8b711",
          "md5": "3e44ff36141513a44fe3c820b96d6b29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "signflinger-4.2.0.jar",
          "url": "signflinger-4.2.0.jar",
          "size": 15208,
          "sha512": "aa911c80e37ee306ef0932954458b5351651de60ed82deac17262a57e8c57f65ff2d7bbdb242cfa53c8ee9008e20c06689bfc7dc0e840baa94bd6ae85f9c49e5",
          "sha256": "87d369493521886d017cbcab0d1be658bab8c006dfb8aebd868b19127839ff22",
          "sha1": "99e94d23459e582bbca3c266465f8cdd1fe8b711",
          "md5": "3e44ff36141513a44fe3c820b96d6b29"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signflinger-4.2.0-javadoc.jar",
          "url": "signflinger-4.2.0-javadoc.jar",
          "size": 28454,
          "sha512": "a496c3f25988a0fe263e75cbebcb5644e41aa8827913950fe05e2db9dd96c5d6e0eff440c50d70d92caed09e4e724045ce1dad5935945ddafb95f0440819a0ba",
          "sha256": "1349a5c65beb1ac1d65901eb9f097e1345fb16fb14f23dfbb4c62114c6f54ffc",
          "sha1": "4648afaf274ad6d9d0b19c309672b387eecadc59",
          "md5": "a6a334c8f846593951858805c85446ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signflinger-4.2.0-sources.jar",
          "url": "signflinger-4.2.0-sources.jar",
          "size": 9341,
          "sha512": "f0c79e5822a3ba70c896d531e4248dcdd0426e4237ef2c44146a83aac127adea35bdfdd9e0ebf0ae2441e6629edc5616b7453008733800c5f0e5e51b131ef321",
          "sha256": "020f92d49281c739807e0cd8e13fabda62895e79ad86a1acd955eb508e825d2e",
          "sha1": "31883e30b96ded4c52b9bda8e277af7fd64debb7",
          "md5": "e4d195857a633028da0eda0381b088bd"
        }
      ]
    }
  ]
}
