{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "common",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "common-27.2.0.jar",
          "url": "common-27.2.0.jar",
          "size": 311051,
          "sha512": "0b89836263ed2036227f459a5670272a3edd8feb9bb6c37e2c6bd52e662196f9d1c1d3eee0aec5acd39864dcc5e21f71d288c1d7ce7233ed1d4e0fc7071d70df",
          "sha256": "5d8b49fe38709f672f970c9d719acc73759b0b82d08d2e46f24dfbf03e98bd8f",
          "sha1": "0b004d1abfcd4c3b83b62a6d672d8e03f0061210",
          "md5": "71fefd0215292d7f18f07776ef30c5c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "common-27.2.0.jar",
          "url": "common-27.2.0.jar",
          "size": 311051,
          "sha512": "0b89836263ed2036227f459a5670272a3edd8feb9bb6c37e2c6bd52e662196f9d1c1d3eee0aec5acd39864dcc5e21f71d288c1d7ce7233ed1d4e0fc7071d70df",
          "sha256": "5d8b49fe38709f672f970c9d719acc73759b0b82d08d2e46f24dfbf03e98bd8f",
          "sha1": "0b004d1abfcd4c3b83b62a6d672d8e03f0061210",
          "md5": "71fefd0215292d7f18f07776ef30c5c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-27.2.0-javadoc.jar",
          "url": "common-27.2.0-javadoc.jar",
          "size": 458791,
          "sha512": "68e607291581f3f8e770ead4a846152352dd7d0503141e85d48f7fcd51a93fa6286b641c538695b7c87723de2120876c64c509dfafdd289958593a15a12fc5a2",
          "sha256": "2cf3c3ba7be6ce02c44e60f8595fd678db6fe5fdeb6ec68979bf29fedffa3d70",
          "sha1": "b9c4ae84af209be2792840b2bb91b8e8a183d6f6",
          "md5": "1573b83c412dcdf221cdda537b1b91ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-27.2.0-sources.jar",
          "url": "common-27.2.0-sources.jar",
          "size": 201905,
          "sha512": "ba0cb52dd95522dd278c5721b38eb058379f7721ed558947f8e1b0af04c2ada3d6adcaeafea8bfb6846f538742175f34eaa837e4d7a7d6958a51339c03031046",
          "sha256": "5e819748dc1710dbfa83f83716c43bf7881d6f310529860da341de1e8cffabbb",
          "sha1": "c28ef583f4b1996b25f6e5eac7b5d1f81248e40c",
          "md5": "91f546c85adb6ff565ee84c84a47476e"
        }
      ]
    }
  ]
}
