{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "crash",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "crash-27.2.0.jar",
          "url": "crash-27.2.0.jar",
          "size": 13616,
          "sha512": "971ad187738f1c632d7da817cf6d74624215aecbe874b5917982414007943e120d40ad032dfc7652d3a8b784a5cf04bede730dd42318be08b42fc86f1f424b7a",
          "sha256": "7ea1eecdd6ecb018ec561651691a61c9123343e4715bca6724d33db5d3c47746",
          "sha1": "6c4a17cac6f9e58882123cccbfd642b0e602f726",
          "md5": "d496a82c07ba6698be90eb763a2ad211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "crash-27.2.0.jar",
          "url": "crash-27.2.0.jar",
          "size": 13616,
          "sha512": "971ad187738f1c632d7da817cf6d74624215aecbe874b5917982414007943e120d40ad032dfc7652d3a8b784a5cf04bede730dd42318be08b42fc86f1f424b7a",
          "sha256": "7ea1eecdd6ecb018ec561651691a61c9123343e4715bca6724d33db5d3c47746",
          "sha1": "6c4a17cac6f9e58882123cccbfd642b0e602f726",
          "md5": "d496a82c07ba6698be90eb763a2ad211"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crash-27.2.0-javadoc.jar",
          "url": "crash-27.2.0-javadoc.jar",
          "size": 31677,
          "sha512": "f273ac59daff8dc1176ea2eb849f127111a544592b4c6da9c4d5109d45d94785125c67fb10bad5711ef7cdf6f2c460a1ebb935dc371b37fe4d8f07d58db1395a",
          "sha256": "c8220f252bd8890300cf93a8b1f94a06b47c4e46f3fa62c013a95d8272cb2f60",
          "sha1": "969edbc492b1656b2ed3ff7c124402e0d25c4f9f",
          "md5": "a04980e57c7e31b17e9bd6695a1a6172"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crash-27.2.0-sources.jar",
          "url": "crash-27.2.0-sources.jar",
          "size": 10684,
          "sha512": "0385411de2a9d51d1a198f2288b758ad35e465adcd2d77aaea538e18b2b69d1d6e0eabc50bab20aad66be83832100ce3d5b26ec9ff50944274027f0ba38e81e5",
          "sha256": "f40bfb527763a9d06605af4c2b0a5d373189d2e2c570a2c6522ad049404f830a",
          "sha1": "101518c2dc9e603839110204aa560b13292a3dd6",
          "md5": "902a397b0c2c11108332ba239ceab0c0"
        }
      ]
    }
  ]
}
