{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-4.2.0.jar",
          "url": "builder-test-api-4.2.0.jar",
          "size": 15492,
          "sha512": "124cc23c6c97848e8c3561b7c8f92084fc02e1258789211f174512835f4ccb27958b988fb0e6238f7bbcf110c9451eadb1bc5e097846a287574a65eef860605a",
          "sha256": "6cf4b5e819cacc109ee0bcd8a149ba75d2ee7c48f4680decb360315e5bc421ae",
          "sha1": "070d70efb44c109513673cd44ea8fc187917ca87",
          "md5": "f760c58656f472f0f5eb0c5ae1e2cc8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-4.2.0.jar",
          "url": "builder-test-api-4.2.0.jar",
          "size": 15492,
          "sha512": "124cc23c6c97848e8c3561b7c8f92084fc02e1258789211f174512835f4ccb27958b988fb0e6238f7bbcf110c9451eadb1bc5e097846a287574a65eef860605a",
          "sha256": "6cf4b5e819cacc109ee0bcd8a149ba75d2ee7c48f4680decb360315e5bc421ae",
          "sha1": "070d70efb44c109513673cd44ea8fc187917ca87",
          "md5": "f760c58656f472f0f5eb0c5ae1e2cc8a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-4.2.0-javadoc.jar",
          "url": "builder-test-api-4.2.0-javadoc.jar",
          "size": 48647,
          "sha512": "a142e60ec405921b461fee9f756824ae879f60a54f030d6738d436e7d6b980d9293723d15c074333c17cd425a613296c83a78264bee3dae0be6ae8baaf7d3037",
          "sha256": "45aebc4ae2a4f3dfa0d09c108fdaab83b07fb28fe1b18aeeb50393a4c46c658b",
          "sha1": "a6d157e41d8e61ca935385e2cdd5dba4a1956d48",
          "md5": "bf65c8344b928898798b05e1e0bb2573"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-4.2.0-sources.jar",
          "url": "builder-test-api-4.2.0-sources.jar",
          "size": 13590,
          "sha512": "16d24a0814a20d644548b3f9e4d31e8dfe07c7246ae0ae28eaac87599e277dd4da06d7be56b3124bddfa2efb41cabc574b806cc0d64d6a86c7c13e0a8e9b099d",
          "sha256": "80a07608921c53b810aabbcf8b74fd5facfbe123069b7f15e2323cc3554acd22",
          "sha1": "18d8e526b44f4220b2a857e4b6f5136c2ec89aba",
          "md5": "43870fc6b0033f6b4e4482a18b604bf4"
        }
      ]
    }
  ]
}
