{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-27.2.0.jar",
          "url": "manifest-merger-27.2.0.jar",
          "size": 205233,
          "sha512": "419e6954fadf2f895e817232bbc209bbe73fb5633dcad15a150ca7e38c2543e1ef5037dc5235130466ec8a9c5295a21c5dd1c57e3b72dd47e4173db9772debb5",
          "sha256": "b4c14da508e3bbc4809bb0d7b063cc389ad72a3835843cc89107a0cdb61c21fb",
          "sha1": "c074b9a439ac617236bc31f978b4520b0fc86fb7",
          "md5": "26653f5404fd75a1561171b111450789"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-27.2.0.jar",
          "url": "manifest-merger-27.2.0.jar",
          "size": 205233,
          "sha512": "419e6954fadf2f895e817232bbc209bbe73fb5633dcad15a150ca7e38c2543e1ef5037dc5235130466ec8a9c5295a21c5dd1c57e3b72dd47e4173db9772debb5",
          "sha256": "b4c14da508e3bbc4809bb0d7b063cc389ad72a3835843cc89107a0cdb61c21fb",
          "sha1": "c074b9a439ac617236bc31f978b4520b0fc86fb7",
          "md5": "26653f5404fd75a1561171b111450789"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-27.2.0-javadoc.jar",
          "url": "manifest-merger-27.2.0-javadoc.jar",
          "size": 183216,
          "sha512": "2baa955861ba9775abd66178684f2411aaa46afb4dbeba6f3fa16178ea36b8fe32cdef66937874e56857d77ac8cdd5a52fc7e010d0a11348bd50c2370db3848c",
          "sha256": "7ced018258ecabae094bb4c37652c907f006adca1c5aebb415d686798015dbc2",
          "sha1": "d8a1ffcdbc75dfd4d5be56d6bc8a8c9c6ae3abdd",
          "md5": "41db425c6e903beee408d9764ccfeec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-27.2.0-sources.jar",
          "url": "manifest-merger-27.2.0-sources.jar",
          "size": 206105,
          "sha512": "2a8a47e9695a1974d7ca442b43d2f5029e7cbd2bb5c1002f76f53233cc0681851fbb4856b7cef533728fffae13048f24e79e5a0399c69786ff9a5d319db9d041",
          "sha256": "7e5704deb45a7fb453589df49644c0085b49806205a47486588c7f784738d416",
          "sha1": "bf90a44a0b3295f1372a285919f64480b6fd32a1",
          "md5": "13752d05a14a187065d251c8ea4ffe71"
        }
      ]
    }
  ]
}
