{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "4.2.0-7147631",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-4.2.0-7147631.jar",
          "url": "aapt2-proto-4.2.0-7147631.jar",
          "size": 673861,
          "sha512": "90b94d00b549050c965854c2d182f743c55931e8d983bdc58d628646fc69ed9d432d87cf31450f704c01067c017ca521c0bf3947181e06b0094e9581ba0ac6bc",
          "sha256": "f3f19ddb52daf1cc3a746f44302b98bd81f074f8a6ac2fc82fdf274c149f8bfb",
          "sha1": "1501d986817b6cef09fc198e8e6ca00a15c13f00",
          "md5": "5615ecc30528f745a2eba48b97bd4a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-4.2.0-7147631.jar",
          "url": "aapt2-proto-4.2.0-7147631.jar",
          "size": 673861,
          "sha512": "90b94d00b549050c965854c2d182f743c55931e8d983bdc58d628646fc69ed9d432d87cf31450f704c01067c017ca521c0bf3947181e06b0094e9581ba0ac6bc",
          "sha256": "f3f19ddb52daf1cc3a746f44302b98bd81f074f8a6ac2fc82fdf274c149f8bfb",
          "sha1": "1501d986817b6cef09fc198e8e6ca00a15c13f00",
          "md5": "5615ecc30528f745a2eba48b97bd4a8b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-4.2.0-7147631-javadoc.jar",
          "url": "aapt2-proto-4.2.0-7147631-javadoc.jar",
          "size": 261,
          "sha512": "3595bfec7d9db185d1a366de685e7d13f81870d01c17d289aabebb4b00fc0b387be1a434d11f9f902b613e167caca32e1e8716345b76ad793f4dcdd2e8c806ef",
          "sha256": "8b160c7e44c1c6eef422fb51abd7642004503def4ef397326e5d4a76047dfbc7",
          "sha1": "c1626fe61396bef093f00ebb54d1a610b0830d4d",
          "md5": "c1598df545dc54f500adf8043a3c2d70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-4.2.0-7147631-sources.jar",
          "url": "aapt2-proto-4.2.0-7147631-sources.jar",
          "size": 181337,
          "sha512": "a75e07d0608624b8c47410ae433072e11daee355512117a08196dcc3222dec3edd47c1ee980cd839e68d8ffd72e08fad7aab27850455aa1185a6f5fa13185114",
          "sha256": "b122ff60e661c1eb145952fdf7ab9142ddfd26da608eae9276b215bb8e6d2a74",
          "sha1": "cfcd63e7cc47a793f4bc7d7d7d0d38acf5c0e8ae",
          "md5": "ce968d091bdb8b8214feb6c28af2287e"
        }
      ]
    }
  ]
}
