{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "dvlib",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dvlib-27.2.0.jar",
          "url": "dvlib-27.2.0.jar",
          "size": 41128,
          "sha512": "38c7470649a0bedd059c42f0cd6a8b0bcebc597928cea6052ae063bc9c9bd71ce5c6d0c43eae628289ff31bd0126051361d6f31fb08951398105d9f3b32044ef",
          "sha256": "7592e65cef7b7b03b9df64a2f059f99c7c173feeba5284f25feb137b6405df96",
          "sha1": "6d43a851ff6f97e3c920a36e9fab10924c9c6dfa",
          "md5": "1009484a1fc172b9b1bb8e2e93917f89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dvlib-27.2.0.jar",
          "url": "dvlib-27.2.0.jar",
          "size": 41128,
          "sha512": "38c7470649a0bedd059c42f0cd6a8b0bcebc597928cea6052ae063bc9c9bd71ce5c6d0c43eae628289ff31bd0126051361d6f31fb08951398105d9f3b32044ef",
          "sha256": "7592e65cef7b7b03b9df64a2f059f99c7c173feeba5284f25feb137b6405df96",
          "sha1": "6d43a851ff6f97e3c920a36e9fab10924c9c6dfa",
          "md5": "1009484a1fc172b9b1bb8e2e93917f89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dvlib-27.2.0-javadoc.jar",
          "url": "dvlib-27.2.0-javadoc.jar",
          "size": 26410,
          "sha512": "0b428a468e26e28ba574d4ac9082479d9772ca70b55dabb6185485d739d187769752f060099a6a37d8cbc91ae4eb69d4286a61bf54a33804a46eb221a69a46ac",
          "sha256": "17a00d815a0bcd00b3516ce581c10e9ea760e1c49d42c4f3b7880c649c381d3d",
          "sha1": "0fd888a113648e4e098168ccc9eb9f823f6da98a",
          "md5": "276f310d9744c5bf12a86e8e79f87167"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dvlib-27.2.0-sources.jar",
          "url": "dvlib-27.2.0-sources.jar",
          "size": 38460,
          "sha512": "10fe82e9a4a8acf68c5ae76c824bb3301b6982231a6ec5232f4362bc0b8bca2f7bdab2340b7e14a2bbaf9469ee576e0593b865f0fe6b8d968f864c63d22c9faf",
          "sha256": "3e1e48bbf95fc13ef8a9e5a242dbc224aacbc5233b000ee5ac8451eea5e07ec3",
          "sha1": "e6202b458f835234fbb7f87ff19243f8158cca20",
          "md5": "03a7abe210d9f865ff01b9b082fbf97b"
        }
      ]
    }
  ]
}
