{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-common",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "databinding-common-4.2.0.jar",
          "url": "databinding-common-4.2.0.jar",
          "size": 16110,
          "sha512": "150aa16d21628a28bfb434716cc15606c9d5894f82d771359402b441e830c1f50485b40685ff47427f63213a9093c84413e5ce69239ad7b2cec840e51b763eb3",
          "sha256": "5644a7d87790c54647da41e385f2c4c74f58dca2dbf451f79ee06ae70ea338ff",
          "sha1": "3723c4679dde4ea48598eda6a4735df5b130efca",
          "md5": "7f6bcd7a66492d3ca94ffc026392b749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-4.2.0.jar",
          "url": "databinding-common-4.2.0.jar",
          "size": 16110,
          "sha512": "150aa16d21628a28bfb434716cc15606c9d5894f82d771359402b441e830c1f50485b40685ff47427f63213a9093c84413e5ce69239ad7b2cec840e51b763eb3",
          "sha256": "5644a7d87790c54647da41e385f2c4c74f58dca2dbf451f79ee06ae70ea338ff",
          "sha1": "3723c4679dde4ea48598eda6a4735df5b130efca",
          "md5": "7f6bcd7a66492d3ca94ffc026392b749"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-4.2.0-javadoc.jar",
          "url": "databinding-common-4.2.0-javadoc.jar",
          "size": 70190,
          "sha512": "0073a7995f952b15d5af946420329d08e9462fa2c4cd712c4e802cb42059af9906c4468f01c5d2165fcdf1d79d493e7cd2c33f916ec392ef109bc41cb02dfd55",
          "sha256": "cd526e62688aac9c3f7b937df82be60e8a9dc87b02c52420b39b1eb3e5b00838",
          "sha1": "d34935d130d2b27bb1b64624f0909d2d3280c7fa",
          "md5": "0150210b8e0bf60ad4eff36b26038daa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-4.2.0-sources.jar",
          "url": "databinding-common-4.2.0-sources.jar",
          "size": 45950,
          "sha512": "509af33b17e6cdb6ae8473bcd38ad0a3d2525754e074e173af4ce0ff6fc31a5241284be1fee69b980fd0d7e469e288236fcef3a57a486e0e0bf2a6b67fe37355",
          "sha256": "3e6f192b7801a0c23433baf0c660efb6f0dd0c0e8895a9afb0fbb00f215f7900",
          "sha1": "401bf945c019c13b0211cccaad20f3e7b62fd315",
          "md5": "c3b0c34acace2865a56b004cbb1c6432"
        }
      ]
    }
  ]
}
