{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apksig",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apksig-4.2.0.jar",
          "url": "apksig-4.2.0.jar",
          "size": 394266,
          "sha512": "73d005014bf891193abb66a700d75107aedc5a89497aa6d25a52d7ef03b27b26f18454be6c1a6dd74a1e7325ecea773d5b641e1cf7495070a02ba2ed05318de6",
          "sha256": "4c8212c60df093f698ed6411f20b30daeace23f6f67d1c5a14273b05a3c074a1",
          "sha1": "98c4358ab08d3ef7cd66c79cc91b632b63fc48ac",
          "md5": "cc6e7aecc93777cbb63302ecb0bec8bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-4.2.0.jar",
          "url": "apksig-4.2.0.jar",
          "size": 394266,
          "sha512": "73d005014bf891193abb66a700d75107aedc5a89497aa6d25a52d7ef03b27b26f18454be6c1a6dd74a1e7325ecea773d5b641e1cf7495070a02ba2ed05318de6",
          "sha256": "4c8212c60df093f698ed6411f20b30daeace23f6f67d1c5a14273b05a3c074a1",
          "sha1": "98c4358ab08d3ef7cd66c79cc91b632b63fc48ac",
          "md5": "cc6e7aecc93777cbb63302ecb0bec8bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-4.2.0-javadoc.jar",
          "url": "apksig-4.2.0-javadoc.jar",
          "size": 206464,
          "sha512": "a569da0c78e3131c774f924687aab44195d52560dc90cc426975ce622e781fe94d675b524f558decb8343616ad6d436692a2afa1eda8623e1ac5cebad24b9305",
          "sha256": "65f02541daebd3042222ad343526b042bfafcb745b22e48fbd8ca005559cd030",
          "sha1": "f95d013d55eb2feb1462fe801c979229ab1ad826",
          "md5": "8001f0aed00757214f179e6a07fdc397"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apksig-4.2.0-sources.jar",
          "url": "apksig-4.2.0-sources.jar",
          "size": 260269,
          "sha512": "540090861ce1a34b1d11b84d86c84976fbc7a5e49114a79fd9324ced967f4af05a8db69bb672e1044ecce12b84a7e11e2ebcc81da98c86bec38e10650e752690",
          "sha256": "0db954fa2c347a15fc7e73ae0bb931a29260995f88efe2d3c1e69820848e345f",
          "sha1": "47170ac6c77b6973bf4e9d01436dbc6c3d921eda",
          "md5": "6b960c3fe50a76df3731262d8e056b85"
        }
      ]
    }
  ]
}
