{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "protos",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-27.2.0.jar",
          "url": "protos-27.2.0.jar",
          "size": 4528442,
          "sha512": "22601aa80f48ed18cd7ae612ff6af396745f58ca1e473326eb1d5b7f0f6e2fdce82326a217353f8675feb9620800433cc62b7398e781fbdc0924811565386c62",
          "sha256": "86f52fc32465b39ad606b0cea3daceee201971491d5404a7354e178194f31d77",
          "sha1": "133ebd79a84b4aecc1e6bf0f90f84064054ae64f",
          "md5": "6a5bcea480634b26b14704b94a4ce3b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-27.2.0.jar",
          "url": "protos-27.2.0.jar",
          "size": 4528442,
          "sha512": "22601aa80f48ed18cd7ae612ff6af396745f58ca1e473326eb1d5b7f0f6e2fdce82326a217353f8675feb9620800433cc62b7398e781fbdc0924811565386c62",
          "sha256": "86f52fc32465b39ad606b0cea3daceee201971491d5404a7354e178194f31d77",
          "sha1": "133ebd79a84b4aecc1e6bf0f90f84064054ae64f",
          "md5": "6a5bcea480634b26b14704b94a4ce3b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-27.2.0-javadoc.jar",
          "url": "protos-27.2.0-javadoc.jar",
          "size": 261,
          "sha512": "0268de321b369b0f17b81aeab8e7a5d55ee8492632280e62eca154fb647d439bb78126bc65ff5003863a098e73e3403278121cbb1c84d029f8aa0083f09b4c3c",
          "sha256": "a62a8fe4e358522811c2c0a4bf714f0e7335b61776ffe03948462cfac7a241b3",
          "sha1": "dcd1ddd911032aa2fdb663457a8f06d010d6abbe",
          "md5": "f85680a9a36c358895fdca713eb260e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-27.2.0-sources.jar",
          "url": "protos-27.2.0-sources.jar",
          "size": 4070,
          "sha512": "42ba4638ac5098a400d05da27280b5cca8518a47aae709b22e9c28218151488fcc439900bcc7214bec0fdd9257533dfbd50637eb4c23d452147612101850b128",
          "sha256": "b6769b15fe3406245e7e3dd539c199f5551fcd3aa7d59a4b4c6c25c9241cf587",
          "sha1": "e8c7afbb36e42c70dfa2b2069854e32dc92f3a66",
          "md5": "2b66a17a6438a618efd76c413ecf1597"
        }
      ]
    }
  ]
}
