{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.0.jar",
          "url": "apkzlib-4.2.0.jar",
          "size": 204415,
          "sha512": "834568e6106c612847c7a48fcb12f5453c038632500e3bbf86ea872b3e84f7d1110f1a0b002ae1bc4824f249d2f3b9aec80930393064151ac6124195ba605248",
          "sha256": "59c71d70754514cf951644797d463d75a6d264795b8c82d4fe0c903da25a57ca",
          "sha1": "49cb407f13ef01fa8b6c21b4429b2f876767f68e",
          "md5": "3ccda09cf8ab12a94f9aaf3328040fc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.0.jar",
          "url": "apkzlib-4.2.0.jar",
          "size": 204415,
          "sha512": "834568e6106c612847c7a48fcb12f5453c038632500e3bbf86ea872b3e84f7d1110f1a0b002ae1bc4824f249d2f3b9aec80930393064151ac6124195ba605248",
          "sha256": "59c71d70754514cf951644797d463d75a6d264795b8c82d4fe0c903da25a57ca",
          "sha1": "49cb407f13ef01fa8b6c21b4429b2f876767f68e",
          "md5": "3ccda09cf8ab12a94f9aaf3328040fc6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.0-javadoc.jar",
          "url": "apkzlib-4.2.0-javadoc.jar",
          "size": 300653,
          "sha512": "049d6aad825fb8d4c829763b89f8fa8c1bcb4f80bd52237657f517af2d72e22d314f8637e108c85fc16f3e587d3d11e8185c99fa062d9556f29515ae3e13f71e",
          "sha256": "89a406a15538749e7ef3b2e56c85cbe62aaaaca910a8db1cb2c1912ec9488aa3",
          "sha1": "baac14013503b8e707b722f11bf95cdd6551f6d2",
          "md5": "18d3e5ca799734e3704e65b767b3ba72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.0-sources.jar",
          "url": "apkzlib-4.2.0-sources.jar",
          "size": 175631,
          "sha512": "40f2e9711e1072659a1f238e281e0cc5d165895fe91de1114abd83508b5d43bafcd11e41f538f3fb229cf4db4b28d1682280a6cc72ed2fe4add946bc9bfa4e62",
          "sha256": "2a45d8184ab048a979b4db05fc2c8baf5a47d1d142c48a7e79ea9a2084e8ae44",
          "sha1": "ac1d8d798cb4bd7325d32c56574b323389e9349f",
          "md5": "c777a272afe4b6cc5d1cc017d07b6b1e"
        }
      ]
    }
  ]
}
