{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "repository",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.sun.activation",
          "module": "javax.activation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.jimfs",
          "module": "jimfs",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "repository-27.2.0.jar",
          "url": "repository-27.2.0.jar",
          "size": 203156,
          "sha512": "e2ddcdfb233a5989e7e21776cfef39ee9d116624a1936b27b9468090a554932b8f102f0ae3c20d4e2eb2feec1bddd52af8caf8cbe60d90b621556415468b0b59",
          "sha256": "8afc3366737582e86f94a6eef2158db348a7f6cff89ddc022c5f3fb7e8ed8dff",
          "sha1": "effd29b0a3597bbc1a9503936fc6814b4cb27213",
          "md5": "664782b59360c3043862c9674c14de67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.sun.activation",
          "module": "javax.activation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.jimfs",
          "module": "jimfs",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "repository-27.2.0.jar",
          "url": "repository-27.2.0.jar",
          "size": 203156,
          "sha512": "e2ddcdfb233a5989e7e21776cfef39ee9d116624a1936b27b9468090a554932b8f102f0ae3c20d4e2eb2feec1bddd52af8caf8cbe60d90b621556415468b0b59",
          "sha256": "8afc3366737582e86f94a6eef2158db348a7f6cff89ddc022c5f3fb7e8ed8dff",
          "sha1": "effd29b0a3597bbc1a9503936fc6814b4cb27213",
          "md5": "664782b59360c3043862c9674c14de67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-27.2.0-javadoc.jar",
          "url": "repository-27.2.0-javadoc.jar",
          "size": 462033,
          "sha512": "ee059d9ed74239f3966433242c0eba6aadfe57dd71248da238e11c9bb6babc546f6390d5a87681954145b74187b8d3c31311ad44c64ab9051fd0c8732edc5511",
          "sha256": "e6aaf6b5653501b474e60272e7e10f4826c3da3815aa2e5c2b0649d87cf0f8ef",
          "sha1": "4994a96f99938fe281b9a69626492bf5c52bcfe9",
          "md5": "646973185fda3e9d37184af7f7f5a640"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-27.2.0-sources.jar",
          "url": "repository-27.2.0-sources.jar",
          "size": 333218,
          "sha512": "e705194dc05b386979ecaff6c3e97d0790c404d4902eaf14659d7309b81882b5fc09d7732f2871492e3f94fcadda8459ef5089ae621ccf393d2fbfeb98951257",
          "sha256": "b73d6d7832822f3d5043c35a1399c6bb15854da35c04db5e4a43873dc1bd9176",
          "sha1": "5aecccddbd208f7796565497e43df810a7aad2c0",
          "md5": "465372a89b7c9abb4dc7d474d419d8d2"
        }
      ]
    }
  ]
}
