{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-4.2.0.jar",
          "url": "gradle-api-4.2.0.jar",
          "size": 174961,
          "sha512": "3e94a337aa0c5f5dc6b998189e59b2c94e297908d867dbcf9389e5b7c99e23494ede6cc5faef803b896171b1608579cc0665e2c3e39da2b6486e81960c63920a",
          "sha256": "8f4bdb1713ea6d6ca1794cb3db98b5587eba5ff3be52d5f51892dc3356f8ae7f",
          "sha1": "57eacf3a9bd9755e77638da57344bea4d45bb251",
          "md5": "94c1def8a36c303b171218b89deb4ee0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-4.2.0.jar",
          "url": "gradle-api-4.2.0.jar",
          "size": 174961,
          "sha512": "3e94a337aa0c5f5dc6b998189e59b2c94e297908d867dbcf9389e5b7c99e23494ede6cc5faef803b896171b1608579cc0665e2c3e39da2b6486e81960c63920a",
          "sha256": "8f4bdb1713ea6d6ca1794cb3db98b5587eba5ff3be52d5f51892dc3356f8ae7f",
          "sha1": "57eacf3a9bd9755e77638da57344bea4d45bb251",
          "md5": "94c1def8a36c303b171218b89deb4ee0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-4.2.0-javadoc.jar",
          "url": "gradle-api-4.2.0-javadoc.jar",
          "size": 83867,
          "sha512": "99609ffea4b3f640fc80f01fbbbce359fee97d1c9f5251c8a1beb182a02e65a7d8c08689ccf5c021bdc95a71d29ba7668f018b31ac265a84ff899e815228376c",
          "sha256": "7094d299ce01af10ebd5d534e233680343e787cb5c65d201281d5e92dcf78643",
          "sha1": "6a1d83a0b5314fa6d470f5bd59b7b75dccb651ca",
          "md5": "b6c4d7f103604f8c01cb86c8c49676e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-4.2.0-sources.jar",
          "url": "gradle-api-4.2.0-sources.jar",
          "size": 187265,
          "sha512": "66f9d6c97d2b15e5266f96479c7211221c6ce41ff5cf0a041d4c1e66ca981ecbc28fc9079f86e373384293e9e4377fab0fa0b54cd084fd4177fc6cb54e9bdde2",
          "sha256": "c5798e6682d9b12de33821217ac2aa6b0a138f71675a8249c67152915dcb700b",
          "sha1": "48b3cdd54e2587ea502f752306dd50c71fae4513",
          "md5": "e44f8dea28e86dad5686d61c30ca6ca6"
        }
      ]
    }
  ]
}
