{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "annotations",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-27.2.0.jar",
          "url": "annotations-27.2.0.jar",
          "size": 10300,
          "sha512": "e4cc9e141e63db6f7df7ebcbd5c16a86cb62f3b1e42b9dfb1498712bcfeb965f762292b38be0feceed1b57112041378326922772ad39b37a319f909d9ef6177c",
          "sha256": "e6b2d3a70ad7543c137ea4c1406a2003259e279d6607c3076018f9b0fd1ded30",
          "sha1": "8994674629f58684e973ac01c570b75bc3725169",
          "md5": "2d3ca408bda07acf93a278d92d394b59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-27.2.0.jar",
          "url": "annotations-27.2.0.jar",
          "size": 10300,
          "sha512": "e4cc9e141e63db6f7df7ebcbd5c16a86cb62f3b1e42b9dfb1498712bcfeb965f762292b38be0feceed1b57112041378326922772ad39b37a319f909d9ef6177c",
          "sha256": "e6b2d3a70ad7543c137ea4c1406a2003259e279d6607c3076018f9b0fd1ded30",
          "sha1": "8994674629f58684e973ac01c570b75bc3725169",
          "md5": "2d3ca408bda07acf93a278d92d394b59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-27.2.0-javadoc.jar",
          "url": "annotations-27.2.0-javadoc.jar",
          "size": 46270,
          "sha512": "e04a8cda18dd3a7a2d56a0f1c6eb22141041d3d28c536134084a5a31b707387189a6935ee52dfa87f53a3fc2f288bd504a1063d3138de3fd734116a38cf92200",
          "sha256": "78a8a573d0a02b765ee52871585ab8e53b24312e28dbb5571cd7f007b17b2eac",
          "sha1": "c4ec64405f04261fc4dab94a7702153dc6d0f9fc",
          "md5": "efd0804c1d5f9427d46227e601677ab8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-27.2.0-sources.jar",
          "url": "annotations-27.2.0-sources.jar",
          "size": 13987,
          "sha512": "3063149ed76aa0479027c0391e01bb45073dcf88eb72fa0e2aebf9636623034b6b0f821047a7c73f93ef193bec75d9054e842ab2567dc162a9dfbae2b9be836d",
          "sha256": "aac40d425e7212d791d69a8d995e701cf95541b2ffe4d604833bda4d14ba4b85",
          "sha1": "03d7c416e71b94f1b9270514b63e4865bde1444d",
          "md5": "d3814de8d13fb9d141442f2a75a0c73c"
        }
      ]
    }
  ]
}
