{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.layoutlib",
    "module": "layoutlib-api",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "layoutlib-api-27.2.0.jar",
          "url": "layoutlib-api-27.2.0.jar",
          "size": 112743,
          "sha512": "d74fce4c7416c0de213bc7cdf7b408ba6ef42a292e0482e077696cf50e531372c6d04e521d0baf13980eb82401986c47a34b60e987d30cfac53fa112ad47eb89",
          "sha256": "9596be2423c04cdb693052b1b83548d87e6efebc2f87ad3730848b022ef06cd4",
          "sha1": "e8e77f698e9b6f26d88207751d5ef65068133a57",
          "md5": "c555b2485c76056355b89260c9cb9197"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "layoutlib-api-27.2.0.jar",
          "url": "layoutlib-api-27.2.0.jar",
          "size": 112743,
          "sha512": "d74fce4c7416c0de213bc7cdf7b408ba6ef42a292e0482e077696cf50e531372c6d04e521d0baf13980eb82401986c47a34b60e987d30cfac53fa112ad47eb89",
          "sha256": "9596be2423c04cdb693052b1b83548d87e6efebc2f87ad3730848b022ef06cd4",
          "sha1": "e8e77f698e9b6f26d88207751d5ef65068133a57",
          "md5": "c555b2485c76056355b89260c9cb9197"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-api-27.2.0-javadoc.jar",
          "url": "layoutlib-api-27.2.0-javadoc.jar",
          "size": 336587,
          "sha512": "3beef1936f1f11c0ac659baf2481e20ab16c3412a6b2254c7e8942a044f310ed73dc416e04a370fc35889e5383d41e0deb2b07d0a6d7a5d33554e87d86399bf3",
          "sha256": "4a4e13477151a0c426245e7f0dea08b9db469339c877b7dd3673d448ce520950",
          "sha1": "b6cb6a07bfbb9677372d966e05adcd5bede47a42",
          "md5": "a4d8f39dabc41461d59f8205d58485b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-api-27.2.0-sources.jar",
          "url": "layoutlib-api-27.2.0-sources.jar",
          "size": 106546,
          "sha512": "c392d143611c00e727eac3b3440c4041b1ef833cfbcc54bdf9cf19d31a6ca97be57b61441da22e0811d1617c8cd1e3f92f105acffc63f5e69635e41e133e489e",
          "sha256": "cf555e9a01291023218c43107588fe8f8f281137c54853dc5a6e60dc4c6ca55f",
          "sha1": "945da35e0ab07d283e8045e395d3e567bd50cc9a",
          "md5": "4be00cae145dbb3b6bcfb8e298ec2b66"
        }
      ]
    }
  ]
}
