{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "4.2.0-7147631"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-4.2.0.jar",
          "url": "aaptcompiler-4.2.0.jar",
          "size": 475860,
          "sha512": "7e81c3c9d5035869b5a8eb0778be0dffc8ad2841488a9cec52f45bc1eb2ead4eec3686036319009daf5ed0f4e14d3661bd5a0c1f06f405fe2395534eca27b199",
          "sha256": "4e555dfe49636e2805a81f495cf675f3c97e10775814a192f9ec4811a0f09bd7",
          "sha1": "6c406a804e2fa1f536ab187d34863dae96dd05d0",
          "md5": "479cfc1a6b92938a8993259438fe2b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "4.2.0-7147631"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-4.2.0.jar",
          "url": "aaptcompiler-4.2.0.jar",
          "size": 475860,
          "sha512": "7e81c3c9d5035869b5a8eb0778be0dffc8ad2841488a9cec52f45bc1eb2ead4eec3686036319009daf5ed0f4e14d3661bd5a0c1f06f405fe2395534eca27b199",
          "sha256": "4e555dfe49636e2805a81f495cf675f3c97e10775814a192f9ec4811a0f09bd7",
          "sha1": "6c406a804e2fa1f536ab187d34863dae96dd05d0",
          "md5": "479cfc1a6b92938a8993259438fe2b26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-4.2.0-javadoc.jar",
          "url": "aaptcompiler-4.2.0-javadoc.jar",
          "size": 18579,
          "sha512": "8b14396fe6b3d4e9fa732015fb04b63db52c9eab5b57af12cb9c5b6001804ad86a1dc6bf97a71b1b9998ac777745d1de5d284b43458c7b487fa973b6057d7c80",
          "sha256": "2a2d80c72893d3a95cf9dc89704aa5db8afd4815c91acf170ad8be5ed11a641b",
          "sha1": "2f7f40d82d863b80e842f47106f917910196cf3c",
          "md5": "f71e85e301e4a6c9267a50cdabd9cca0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-4.2.0-sources.jar",
          "url": "aaptcompiler-4.2.0-sources.jar",
          "size": 148922,
          "sha512": "27264affcdd8d7a33a8a44134e44d85035419f8aab578cccd1556a50b118b959059866ff9c0b87c9bc7129466ab9bfe88674ee598fa1fd074879eccb05ae79e8",
          "sha256": "b5c8f71769addfa9eb37b23322bad7beea7927972eff4c52a347987161336181",
          "sha1": "c2de5ea14b0088ed2f39332551437b88941b0306",
          "md5": "e646c77da7655a34aaaae4f74f95ff28"
        }
      ]
    }
  ]
}
