{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android",
    "module": "zipflinger",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "zipflinger-4.2.0.jar",
          "url": "zipflinger-4.2.0.jar",
          "size": 54778,
          "sha512": "31c25c11a08236ce67fea73c45eee6081ccca0c8f1350fcea04be6186983c583330629b7147bfb301d7be1f3e61efd78eb76295e2ade0c80650077acb7e3eb67",
          "sha256": "d5f7b55f2371e19338e5947157a109b9a88d41bb48e4677b98be464354be15dc",
          "sha1": "b9f6661c53cf54fa868db832d2847d7af96d3dc5",
          "md5": "ee7f4767d5bc4d9151e6229aed0b7664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "zipflinger-4.2.0.jar",
          "url": "zipflinger-4.2.0.jar",
          "size": 54778,
          "sha512": "31c25c11a08236ce67fea73c45eee6081ccca0c8f1350fcea04be6186983c583330629b7147bfb301d7be1f3e61efd78eb76295e2ade0c80650077acb7e3eb67",
          "sha256": "d5f7b55f2371e19338e5947157a109b9a88d41bb48e4677b98be464354be15dc",
          "sha1": "b9f6661c53cf54fa868db832d2847d7af96d3dc5",
          "md5": "ee7f4767d5bc4d9151e6229aed0b7664"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zipflinger-4.2.0-javadoc.jar",
          "url": "zipflinger-4.2.0-javadoc.jar",
          "size": 84936,
          "sha512": "fffc980b7777116054e60c20cb27dc928a8c08c4e89be06b9eeb71ea7d7a7bf445a254bd7ff79301facc17337a8b1cb7b34f37e27ae9c2a7d355fc6a15f651b0",
          "sha256": "481a68ad69be65c51875245bc2488364a942dd15e0c113ef5dad56d845f5bb40",
          "sha1": "c908eb45372ce0bd75d8098bdb22e34144bf34c9",
          "md5": "5621290f8a41638307f6c8b2b812fd6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zipflinger-4.2.0-sources.jar",
          "url": "zipflinger-4.2.0-sources.jar",
          "size": 43534,
          "sha512": "2e702c9fc1402dfef0a3a5fd4fc5781abdfd451884c35c98e1e3561db18de42be5397e7352746d9e43e9f142bc05a0f9508adf93244e0a236ded8b4840054147",
          "sha256": "09a811399094dbf65127124c290a790044bf34dde46f6612f472af01c8d5b537",
          "sha1": "1d8174e3ac5e8519e350c39862e1b63717125206",
          "md5": "c470990e021d1039fdf6d942a9dfd298"
        }
      ]
    }
  ]
}
