{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "shared",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-27.2.0.jar",
          "url": "shared-27.2.0.jar",
          "size": 107630,
          "sha512": "83f8dc8a6be428a6451196482dad44c030c7b140b6c7a2dc5606b2856278d8575295bda0619b0cf4b7e658c0e98a63ce870a10ce860b1a5542507223f83ea9ed",
          "sha256": "ad56b84f23b80e8c9252ed97f6d3ccb5f2354794bc45aea0dcec1c004c791438",
          "sha1": "eb396a103c26535b63bad79ed84ec082351a0764",
          "md5": "a00dc3dee84d61e716af27db57107fbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-27.2.0.jar",
          "url": "shared-27.2.0.jar",
          "size": 107630,
          "sha512": "83f8dc8a6be428a6451196482dad44c030c7b140b6c7a2dc5606b2856278d8575295bda0619b0cf4b7e658c0e98a63ce870a10ce860b1a5542507223f83ea9ed",
          "sha256": "ad56b84f23b80e8c9252ed97f6d3ccb5f2354794bc45aea0dcec1c004c791438",
          "sha1": "eb396a103c26535b63bad79ed84ec082351a0764",
          "md5": "a00dc3dee84d61e716af27db57107fbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-27.2.0-javadoc.jar",
          "url": "shared-27.2.0-javadoc.jar",
          "size": 261,
          "sha512": "114f1e9731f54d96baf4d23baef35de3b1c81a643ee5c1a279e32a71e678be9108c91dcf10cb0321118ba83467b39fcea9fd1ad4f0cb3c92771a1515be42335f",
          "sha256": "f81fa78cb73ddefbcd211e7a334f69167fc19e811453944802caaf1dc2da3e58",
          "sha1": "506a37e291a702d5724418dda8c40f9ac68c182d",
          "md5": "fc5f2122c7754b5398b138d0ff8b6ad1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-27.2.0-sources.jar",
          "url": "shared-27.2.0-sources.jar",
          "size": 22238,
          "sha512": "3ebade82be5aa54cac6ea9943561492191b4cfd0c43ee236ee0af2b586ccd21082dadc899fe5db7551fe7ec29ca039b88d6b44d61e37d6a84c4666c45dccdefb",
          "sha256": "7719bd494701689c0cc7c8d4a2e9f82af80ed4173ff65265a012de613e3cfcad",
          "sha1": "a74fca652c8ce3f9211b55c241afa11deb4747c1",
          "md5": "873565f46a06a3ea1d031c08f3813ee4"
        }
      ]
    }
  ]
}
