{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler-common",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-common-4.2.0.jar",
          "url": "databinding-compiler-common-4.2.0.jar",
          "size": 484234,
          "sha512": "ae79c2f5b39e2a06d9661dd07ea1ab83d87ef80031e49f09f7d21b29520b9b130ab0dee465dca0d9295b095cd6ab5be90c4f11c5da5d021f2096fd6e314d3d2a",
          "sha256": "0886c32fada2f8b20b2e778d56605f858171baa326ed04f8d3b1f94ab6f94d15",
          "sha1": "f2f0bebb7cd57cf7440aa99cdf02d066c2a390d6",
          "md5": "660215d056fb77ec0552e2e778d8d300"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-common-4.2.0.jar",
          "url": "databinding-compiler-common-4.2.0.jar",
          "size": 484234,
          "sha512": "ae79c2f5b39e2a06d9661dd07ea1ab83d87ef80031e49f09f7d21b29520b9b130ab0dee465dca0d9295b095cd6ab5be90c4f11c5da5d021f2096fd6e314d3d2a",
          "sha256": "0886c32fada2f8b20b2e778d56605f858171baa326ed04f8d3b1f94ab6f94d15",
          "sha1": "f2f0bebb7cd57cf7440aa99cdf02d066c2a390d6",
          "md5": "660215d056fb77ec0552e2e778d8d300"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-4.2.0-javadoc.jar",
          "url": "databinding-compiler-common-4.2.0-javadoc.jar",
          "size": 421069,
          "sha512": "d3d206be9a0cebffcf7e9150bfc82750c6720faa74a895ad9fd72ca7d0e77df6332bdf2c8519a0c4220c6464b34dd35c7765377a0875c984d084ae4edb20036b",
          "sha256": "00c201d95e38259b0730a6dee874cd124296bbe8415983ff149c253af425b4dd",
          "sha1": "2cd9428416d63450f2b22a56878e1c06155dd4f3",
          "md5": "a3552e28ec35764d1e86cc5e1524b54e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-4.2.0-sources.jar",
          "url": "databinding-compiler-common-4.2.0-sources.jar",
          "size": 196904,
          "sha512": "e6cfde0499419823cab3e57979f5bbf4ecff2f52ec0196c954de63ec0c41f3ad9b0c9176f40428f8858f6f0a2f3246fc7cc02e78dee4e64031a5699fa3bf32f0",
          "sha256": "f720f0ee257a06099da9bbc0af33db547054210794320145d93467ad542d16c2",
          "sha1": "145fd8dca482371748e44039f1cae43359f5b66e",
          "md5": "0a49ae4299fdcf15ebcfc6cf9d894f5b"
        }
      ]
    }
  ]
}
