{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.ddms",
    "module": "ddmlib",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-27.2.0.jar",
          "url": "ddmlib-27.2.0.jar",
          "size": 483826,
          "sha512": "fd3aee376f7eeeb8978602adc75da987acc78599035771eda09a9c5b3dc43112f2bc5c6721af88489bfcb60c364b0462230f8ceef0587f7122aa5826c96f5a85",
          "sha256": "8d0a5af38e1ad340e8df9f028d282a05c704383ed5162c68da444ac92d3376b6",
          "sha1": "59661295b59ef744dd5f2821573c2396a009e974",
          "md5": "14f3acd0d1f7af4c7cfafe6abf451a61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-27.2.0.jar",
          "url": "ddmlib-27.2.0.jar",
          "size": 483826,
          "sha512": "fd3aee376f7eeeb8978602adc75da987acc78599035771eda09a9c5b3dc43112f2bc5c6721af88489bfcb60c364b0462230f8ceef0587f7122aa5826c96f5a85",
          "sha256": "8d0a5af38e1ad340e8df9f028d282a05c704383ed5162c68da444ac92d3376b6",
          "sha1": "59661295b59ef744dd5f2821573c2396a009e974",
          "md5": "14f3acd0d1f7af4c7cfafe6abf451a61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-27.2.0-javadoc.jar",
          "url": "ddmlib-27.2.0-javadoc.jar",
          "size": 556211,
          "sha512": "18b4ee5412c30508e5bf8842c99b9edfe3f3c6c36fc79d2df016dbe30710aa5e7a7b7f745baa659292bbc6ada59ba4f1e2bd26bd352e6ac095d69d63c648bc9c",
          "sha256": "a312381d7831fd29f5ca47f4f7d22647d12f5b320095cc2f8ca820d29ad4c909",
          "sha1": "371496250d78b00ca52ca997be599e3b2883731f",
          "md5": "18b44dc8f41c80b45014f00533d32f16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-27.2.0-sources.jar",
          "url": "ddmlib-27.2.0-sources.jar",
          "size": 607992,
          "sha512": "2853f685d9e9c33c3deb13512853b920c88854e724c4b02522c62af3bb95cee0cd29ae77c3b88ef8570b22cca6d47d283941135b3488d22513fe3a1af35aba12",
          "sha256": "91774ba273c6dc220d6e111660731577697ec12d6e4d6680036f7bea0fbc101b",
          "sha1": "be2bad386312454fd5eb1d4ada765619803c3aed",
          "md5": "d54ce1bc7bbc66884c0194063e6fcd2e"
        }
      ]
    }
  ]
}
